### ISSUE TITLE
AutoDeploy does not work anymore 

### ISSUE THREAD

**Issue by Tondorian** [Pathoschild/Stardew.ModBuildConfig#5]
I am not sure why this happen but after I updated ModBuildConfig 1.4.0 to 1.6.2 VS2017 does not copy my mod to StardewValley after downgrading to 1.5.0 it works again.

Some additonal infos:
ModBuildConfig 1.5.0 works fine, too
ModBuildConfig 1.6.0 works does not work

**Comment by Pathoschild** [comment]
This was caused by an issue with the project file; discussed and fixed over Discord. :)
